# -*- coding: utf-8 -*-
"""DAScep.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kkxFQneExsw6u9zott1qgzhjgjdE7MHZ
"""

set.seed(123)


n <- 1000

transaction_amounts <- rnorm(n, mean = 100, sd = 20)


fraud_labels <- sample(c(0, 1), size = n, replace = TRUE, prob = c(0.9, 0.1))

transaction_times <- sample(0:23, size = n, replace = TRUE)


merchant_ids <- sample(1:100, size = n, replace = TRUE)


customer_ids <- sample(1:500, size = n, replace = TRUE)

locations <- sample(c("New York", "Los Angeles", "Chicago", "Houston", "Phoenix"), size = n, replace = TRUE)

transaction_types <- sample(c("online", "in-store"), size = n, replace = TRUE)

days_of_week <- sample(c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"), size = n, replace = TRUE)

transaction_duration <- rnorm(n, mean = 30, sd = 10)

customer_ages <- sample(18:70, size = n, replace = TRUE)

transactions <- data.frame(
  amount = transaction_amounts,
  fraud = fraud_labels,
  time = transaction_times,
  merchant_id = merchant_ids,
  customer_id = customer_ids,
  location = locations,
  transaction_type = transaction_types,
  day = days_of_week,
  duration = transaction_duration,
  age = customer_ages
)

head(transactions)
summary(transactions)

transactions$z_score <- scale(transactions$amount)

anomaly_threshold <- 2.5

transactions$fraud_detected <- ifelse(abs(transactions$z_score) > anomaly_threshold, 1, 0)

potential_fraud_cases <- transactions[transactions$fraud_detected == 1, ]

head(potential_fraud_cases)

library(ggplot2)

ggplot(transactions, aes(x = amount, y = z_score)) +
  geom_point(aes(color = factor(fraud_detected), shape = factor(transaction_type), size = duration, fill = age), alpha = 0.6) +
  scale_color_manual(values = c("blue", "red"), labels = c("Legitimate", "Potential Fraud")) +
  scale_shape_manual(values = c(16, 17), labels = c("Online", "In-store")) +
  scale_fill_gradient(low = "yellow", high = "red", name = "Customer Age") +
  labs(title = "Transaction Amount vs Z-score (Potential Fraud)",
       x = "Transaction Amount",
       y = "Z-score",
       color = "Fraud Detection",
       shape = "Transaction Type",
       size = "Transaction Duration",
       fill = "Customer Age") +
  theme_minimal() +
  theme(legend.position = "bottom") +
  facet_wrap(~ location) +
  guides(
    color = guide_legend(order = 1),
    shape = guide_legend(order = 2),
    size = guide_legend(order = 3),
    fill = guide_colorbar(order = 4)
  )